use_frameworks!

platform :ios, '9.0'

target 'CGBoxView_Example' do
  pod 'CGBoxView', :path => '../'

  target 'CGBoxView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
